### ISSUE TITLE
outputters seem to fail presumably when result list is empty

### ISSUE THREAD

**Issue by rtrox** [rtrox/mssqlcli#68]
Received an email complaint of the following bug:

```
# mssqlcli -o csv query infoQuery.sql
Traceback (most recent call last):
  File "/usr/local/bin/mssqlcli", line 9, in <module>
    load_entry_point('mssqlcli==1.0.2', 'console_scripts', 'mssqlcli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mssqlcli/cli.py", line 83, in query
    output = ctx.obj['output_formatter'](results)
  File "/usr/local/lib/python2.7/dist-packages/mssqlcli/formats.py", line 81, in csvify
    fieldnames = obj[0].keys()
IndexError: list index out of range
 
When I run it without trying to dump to a .csv file, I get:

# mssqlcli query infoQuery.sql
Traceback (most recent call last):
  File "/usr/local/bin/mssqlcli", line 9, in <module>
    load_entry_point('mssqlcli==1.0.2', 'console_scripts', 'mssqlcli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mssqlcli/cli.py", line 83, in query
    output = ctx.obj['output_formatter'](results)
  File "/usr/local/lib/python2.7/dist-packages/mssqlcli/formats.py", line 101, in pretty_print
    table = PrettyTable(obj[0].keys())
IndexError: list index out of range
```

**Comment by piotch** [comment]
Hello, I also had this error with an empty result set. Maybe the solution is to use the `cursor.decription` instead of the `keys` of the first object. 

https://www.python.org/dev/peps/pep-0249/#description
https://github.com/pymssql/pymssql/blob/master/src/pymssql.pyx#L347

**Comment by rtrox** [comment]
ah, looks like a perfect solution.
